[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#00FF00"
backgroundColor = "#1E1E1E"
secondaryBackgroundColor = "#2E2E2E"
textColor = "#FFFFFF" 